### ISSUE TITLE
Greetings from Artemis project

### ISSUE THREAD

**Issue by zonr** [travelgateX/presenters-benchmark#1]
Hi! This is actually not an issue but a writeup to show ~~off~~ the benchmark results of
the side project I'm working on named [Artemis](https://github.com/botobag/artemis/). Artemis is, yet another GraphQL implementation for Go. It's built with performance in mind and is still in its infancy. We still need to finish validation, introspection and [SDL](https://facebook.github.io/graphql/June2018/#TypeSystemDefinition) support to become a GraphQL server implementation compilance with the specification. Our goal (dream?) is to provide a complete toolkit/library/framework like [Apollo GraphQL](https://github.com/apollographql) to make building production-grade GraphQL services/tools/products easy. The features include but are not limited to stream-based subscription, tracing, query complexity/depth analysis, rate limit (like [GitHub](https://developer.github.com/v4/guides/resource-limitations/#rate-limit)), etc..

Recently, I finished the execution engine (which includes support for non-blocking field resolver, data loaders and parallel execution, all of which are integrated in Artemis project) and were looking for benchmarks to measure how well we've done, to see what else is missing and to compare with other implementation. Fortunately, your report in 99designs/gqlgen#520 led me to this awesome benchmark.

I then spent some time adding [Artemis candidate](https://github.com/botobag/travelgatex-graphql-benchmark/commit/fed5d5d18c97571ef1393323021fc8356643412c) and gets the numbers today which I can't wait to share with you as below. All works and results can be found in [botobag/travelgatex-graphql-benchmark](https://github.com/botobag/travelgatex-graphql-benchmark).

The results look promising. In the benchmark, Artemis outperforms gophers and gqlgen in terms of both execution time and memory usage.

(All numbers are from [`BenchmarkSequential`](https://github.com/botobag/travelgatex-graphql-benchmark/blob/b44e34a/README.md#sample) and use service models for gqlgen)

### Speedup 

... by normalizing execution time of Gophers to 1; **Larger is better**; read as "for the 1-node benchmark, GQLGen is 2.36x faster and Artemis is 3.94x faster compared to Gophers."

 \# of nodes | Gophers    | GQLGen   | Artemis
----------- | ---------- | ---------- | ---------
1                 | 1                | 2.36          | 3.94
32              | 1                | 1.57           | 2.77
1024          | 1                | 1.33           | 2.55
16384        | 1                | 1.20           | 2.34
32768        | 1                | 1.11            | 2.14
65536        | 1                | 1.14           | 2.18

![1](https://user-images.githubusercontent.com/287446/52962854-50eadd80-33d9-11e9-9193-1868e5c31776.png)

### Number of Memory Allocations

... by normalizing allocs/op of Gophers to 100%. **Smaller is better**; read as "for the 1-node benchmark, there're 33% less memory allocations occurred in GQLGen and 54% less in Artemis compared to Gophers."

 \# of nodes | Gophers    | GQLGen   | Artemis
----------- | ----------- | ---------- | ---------
1                 | 100%          | 67%          | 46%
32              | 100%           | 114%        | 29%
1024          | 100%           | 118%        | 27%
16384        | 100%           | 119%        | 27%
32768        | 100%           | 119%        | 27%
65536        | 100%           | 119%        | 27%

![1](https://user-images.githubusercontent.com/287446/52968314-c8276e00-33e7-11e9-97b4-9c88a921bfb9.png)

### Allocation Size

... by normalizing B/op of Gophers to 100%. **Smaller is better**; read as "for the 1-node benchmark, GQLGen and Artemis consume 24% and 20% of memory usage by Gophers, respectively."

 \# of nodes | Gophers    | GQLGen   | Artemis
----------- | ----------- | ---------- | ---------
1                 | 100%          | 24%          | 20%
32              | 100%           | 97%         | 28%
1024          | 100%           | 121%        | 30%
16384        | 100%           | 119%        | 30%
32768        | 100%           | 119%        | 30%
65536        | 100%           | 119%        | 30%

![1](https://user-images.githubusercontent.com/287446/52968337-d70e2080-33e7-11e9-94b1-440b6a7578e3.png)

Please feel free to let me know your thoughts. Artemis cannot grow up to a better project without your feedbacks. Hope you'll find it's interesting and useful!

**Comment by pperaltaisern** [comment]
Hello! Thank you for contacting with us, we are happy to see the activity of the graphql community. We do really like GraphQL but it has the big performance downside. Although we are still using graphql in most of our services, we have been moving to other alternatives in our most critical ones.

Definitely, the decision to use or not graph might depend on whether the existing implementations are good enough for our objectives. So we are going to be attentive to your implementation in the future.

**Comment by zonr** [comment]
Thanks for sharing the findings on performance issue (would like to know more detail about it if possible) and for letting me know the decision. I will keep working hard on providing production-grade implementation. Really appriciate your attention :)
